spring:
  profiles:
    active: local

# mybatis
mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.example.springbootcommonusage.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

mybatis-plus:
  global-config:
    db-config:
      # 更新为null的值
      field-strategy: IGNORED